name: Wheels

on:
  push:
    branches:
      - master
      - stable
      - docs
      - actions*
    tags:
      - v*
  workflow_dispatch:

jobs:
  sdist:
    name: Source distribution
    runs-on: windows-latest
    if: startsWith(github.ref_name, 'docs') != true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.0

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build
          pip install twine check-manifest

      - name: build
        run: |
          make

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_binary
          path: build/all/*.pyd
          
      - name: Build sdist
        run: |
          python3 -m build --sdist --outdir wheelhouse

      - name: Install from sdist
        run: |
          pip install --compiler=mingw64 wheelhouse/ecl-0.0.1.tar.gz

      - name: Check sdist
        run: |
          python3 -m twine check wheelhouse/*

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: wheelhouse/*.tar.gz
