name: Wheels

on:
  push:
    branches:
      - master
      - stable
      - docs
      - actions*
    tags:
      - v*
  workflow_dispatch:

jobs:
  sdist:
    name: Source distribution
    runs-on: macos-latest
    if: startsWith(github.ref_name, 'docs') != true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
        
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.0

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build

      #- name: build
        #run: |
          #make
      - name: Set deployment target (macOS)
        run: echo "MACOSX_DEPLOYMENT_TARGET=12.0" >> $GITHUB_ENV 

      - name: Build wheel
        run: |
          python3 -m build --wheel --outdir wheelhouse
        
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: wheelhouse/*.whl

      - name: Install and import ecl
        run: |
          python -m pip install --no-index --no-deps wheelhouse/*.whl
          python3 -c 'import ecl'
